name: Deploy to Stage Environment

on:
  push:
    branches: [ "stage" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: stage
      stack_name: snipe-ballistics-web-ui-stage
      deploy_cloudfront: "true"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
